import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';
import { ClarityModule } from '@clr/angular';
import ArrowRight16 from '@carbon/icons/es/arrow--right/16';
import CheckmarkFilled16 from '@carbon/icons/es/checkmark--filled/16';
import WarningAltFilled16 from '@carbon/icons/es/warning--alt--filled/16';
import Pending16 from '@carbon/icons/es/pending/16';
import Commit16 from '@carbon/icons/es/commit/16';
import Renew16 from '@carbon/icons/es/renew/16';
import { ActivatedRoute } from '@angular/router';
import { HttpService } from '../core/http.service';
import { BackendUnavailable } from '../os/backend-unavailable';
import { CarbonIcon } from '../os/carbon-icon';
import { OsPageHeader } from '../os/os-page-header';

interface Approval { approver_id: string; status: string; created_at: string; completed_at: string | null; error_code: string | null; }
interface ChangeRequest {
  request_id: string; action: string; target: string; reason: string; status: string; git_repo: string | null; git_ref: string | null; git_commit_sha: string | null; k8s_operation_id: string | null; created_at: string; completed_at: string | null;
  execution: { branch: string; pull_number: number | null; pull_url: string | null; desired_revision: string | null; merge_revision: string | null; reconciler: string; reconciler_status: string; drift_status: string; attempt_count: number; last_error: string | null; updated_at: string } | null;
  outbox: { status: string; attempts: number; next_attempt_at: string | null; last_error: string | null; updated_at: string } | null;
  approvals: Approval[];
}
interface Contract { consumer_id: string; display_name: string; owner_kind: string; supabase_schemas: string[]; storage_buckets: string[]; gitea_repository: string; gitea_path: string; reconciler: string; status: string; desired_revision: string | null; applied_revision: string | null; observability: { phase: string; binding_name: string | null; observed_at: string | null } | null; }
interface Receipt { delivery_id: string; event_type: string; repository: string | null; request_id: string | null; signature_valid: boolean; disposition: string; error_code: string | null; received_at: string; }
interface Repository { name: string; private: boolean; archived: boolean; empty: boolean; defaultBranch: string; updatedAt: string | null; sizeKiB: number; }
interface RecoveryCheck { assertion: string; expected: string; observed: string; verdict: string; }
interface RecoveryUnit { state: string; declaredState?: string; verifiedAt: string | null; assertions: string[]; checks?: RecoveryCheck[]; evidenceQuality?: string; }
interface JourneyItem { key: string; label: string; evidence: string; state: 'done' | 'waiting' | 'failed'; }
interface ChangeTemplate {
  id: string; displayName: string; consumerId: string; action: string; target: string;
  reasonPlaceholder: string; returnTo: string; desiredState: Record<string, unknown>;
}
interface ChangeControlState {
  meta: { source: 'gitea'; checkedAt: string; organization: string; tokenConfigured: boolean }; configured: boolean; ready: boolean; version: string; repositoryCount: number | null; repositories: Repository[]; contracts: Contract[]; receipts: Receipt[]; changes: ChangeRequest[]; byStatus: Record<string, number>; reason: string; managementReady: boolean;
  supplyChain: { repository: string; defaultBranch: string; protected: boolean; requiredApprovals: number; directPushEnabled: boolean; signedCommitsRequired: boolean; blockRejectedReviews: boolean } | null;
  recovery?: { available: boolean; reason?: string; generatedAt?: string | null; gitea?: RecoveryUnit; legacyDecommission?: { approved: boolean; completedAt: string | null } };
}

@Component({
  selector: 'os-admin-change-control', imports: [ClarityModule, BackendUnavailable, CarbonIcon, OsPageHeader], changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    <div class="os-page control-detail-page change-control-page">
      <os-page-header title="Change Control" tag="Gitea · Declarative Change Authority" />
      @if (down(); as detail) {
        <os-backend-unavailable feature="Gitea Change Control" backend="opensphere-console-backend (/api/platform/gitea/status)" hint="Console Backend와 Gitea 연결을 복구하세요. 서비스 토큰·webhook secret은 Secret으로만 제공해야 합니다." [detail]="detail" />
      } @else if (state(); as current) {
        <div class="page-lead"><p>원하는 상태, diff·review·서명 commit·revert의 정본은 Gitea입니다. Supabase는 요청·승인·감사·outbox 상관관계를 보존하고, Kubernetes는 승인된 reconciler의 실제 반영 결과만 보고합니다.</p><div class="page-meta"><span>마지막 확인</span><strong>{{ formatDate(current.meta.checkedAt) }}</strong><button class="icon-button" type="button" aria-label="Gitea 상태 새로고침" [disabled]="busy()" (click)="refresh()"><os-cicon [icon]="icons.renew" [size]="16" /></button></div></div>
        @if (message(); as item) { <clr-alert [clrAlertType]="item.type" [clrAlertClosable]="true" (clrAlertClosedChange)="message.set(null)"><clr-alert-item><span class="alert-text">{{ item.text }}</span></clr-alert-item></clr-alert> }
        @if (requestedTemplate(); as template) { <clr-alert clrAlertType="info" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text"><strong>{{ template.displayName }}</strong> 요청서가 자동으로 준비되었습니다. 버전·chart digest·적용 구성은 변경할 수 없으며, 사유 입력 후 PR을 생성하면 두 번째 운영자 승인 뒤 전용 reconciler가 설치와 Ready 검증을 수행합니다.</span></clr-alert-item></clr-alert> }
        @if (!current.configured || !current.ready || !current.managementReady) { <clr-alert [clrAlertType]="current.ready ? 'warning' : 'danger'" [clrAlertClosable]="false"><clr-alert-item><span class="alert-text">{{ current.reason || 'Gitea governed-change 경로가 아직 준비되지 않았습니다. 조회는 가능하지만 새 변경·승인·반영은 중지됩니다.' }}</span></clr-alert-item></clr-alert> }

        <section class="status-rail" aria-label="Gitea 운영 상태">
          <div class="rail-cell"><span>Gitea</span><strong [class]="statusClass(current.ready ? 'Connected' : 'Unavailable')"><os-cicon [icon]="current.ready ? icons.check : icons.warning" [size]="14" />{{ current.ready ? 'Connected' : 'Unavailable' }}</strong><small>{{ current.version || current.reason }}</small></div>
          <div class="rail-cell"><span>Repositories</span><strong>{{ current.repositoryCount ?? '—' }}</strong><small>{{ current.meta.organization }}</small></div>
          <div class="rail-cell"><span>Open lifecycle</span><strong>{{ inFlight(current) }}</strong><small>intent · authorized · committed</small></div>
          <div class="rail-cell"><span>Approvals</span><strong>{{ approvedCount(current) }}</strong><small>{{ current.supplyChain?.requiredApprovals || 0 }} required per change</small></div>
          <div class="rail-cell"><span>Webhook receipts</span><strong>{{ current.receipts.length }}</strong><small>HMAC verified metadata</small></div>
          <div class="rail-cell"><span>Observed / failed</span><strong [class]="statusClass((current.byStatus['failed'] || 0) ? 'Failed' : 'Observed')">{{ current.byStatus['applied'] || 0 }} / {{ current.byStatus['failed'] || 0 }}</strong><small>Kubernetes receipt truth</small></div>
        </section>

        <nav class="workspace-tabs" role="tablist" aria-label="Change Control 작업영역">
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'overview'" [class.active]="activeTab() === 'overview'" (click)="activeTab.set('overview')"><span>01</span>Overview<small>권위와 준비 상태</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'journey'" [class.active]="activeTab() === 'journey'" (click)="activeTab.set('journey')"><span>02</span>Change Journey<small>요청에서 관측까지</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'repositories'" [class.active]="activeTab() === 'repositories'" (click)="activeTab.set('repositories')"><span>03</span>Repositories<small>정본 저장소</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'changes'" [class.active]="activeTab() === 'changes'" (click)="activeTab.set('changes')"><span>04</span>Changes<small>선언 변경 생성</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'approval'" [class.active]="activeTab() === 'approval'" (click)="activeTab.set('approval')"><span>05</span>Approval &amp; Reconciliation<small>승인·반영 증거</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'webhooks'" [class.active]="activeTab() === 'webhooks'" (click)="activeTab.set('webhooks')"><span>06</span>Webhooks<small>전달 영수증</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'supply-chain'" [class.active]="activeTab() === 'supply-chain'" (click)="activeTab.set('supply-chain')"><span>07</span>Supply Chain<small>서명·브랜치 정책</small></button>
          <button type="button" role="tab" [attr.aria-selected]="activeTab() === 'dr-contracts'" [class.active]="activeTab() === 'dr-contracts'" (click)="activeTab.set('dr-contracts')"><span>08</span>DR &amp; Contracts<small>복구·소비자 계약</small></button>
        </nav>

        @if (activeTab() === 'overview') {
          <section class="domain-workspace" role="tabpanel" aria-label="Overview">
            <div class="overview-surface"><section class="os-card"><div class="os-card-h">변경 체인</div><div class="chain"><span>Supabase intent</span><os-cicon [icon]="icons.arrow" [size]="14" /><span>Gitea signed PR</span><os-cicon [icon]="icons.arrow" [size]="14" /><span>second operator approval</span><os-cicon [icon]="icons.arrow" [size]="14" /><span>webhook + outbox</span><os-cicon [icon]="icons.arrow" [size]="14" /><span>reconciler receipt</span></div><p class="os-sub">한 단계라도 증거가 없으면 완료로 표시하지 않습니다. Browser/OAA는 Gitea 토큰과 reconciler credential을 받지 않습니다.</p></section>
            <div class="overview-columns"><section class="os-card"><div class="os-card-h">Authority boundaries</div><div class="property"><span>Data & identity</span><strong>Supabase</strong></div><div class="property"><span>Change declaration</span><strong>Gitea</strong></div><div class="property"><span>Runtime truth</span><strong>Kubernetes observed state</strong></div><div class="property"><span>Telemetry</span><strong>{{ boundContractCount(current) ? 'HIS Bound' : 'NotConfigured' }}</strong></div></section><section class="os-card"><div class="os-card-h">Management readiness</div><div class="property"><span>Repository</span><strong>{{ current.supplyChain?.repository || 'inventory unavailable' }}</strong></div><div class="property"><span>Protected branch</span><strong [class]="statusClass(current.supplyChain?.protected ? 'Enforced' : 'Missing')">{{ current.supplyChain?.defaultBranch || '—' }} · {{ current.supplyChain?.protected ? 'Enforced' : 'Missing' }}</strong></div><div class="property"><span>Signed commits / direct push</span><strong [class]="statusClass(current.supplyChain?.signedCommitsRequired && !current.supplyChain?.directPushEnabled ? 'Enforced' : 'Attention required')">{{ current.supplyChain?.signedCommitsRequired ? 'Required' : 'Not enforced' }} · {{ current.supplyChain?.directPushEnabled ? 'Allowed' : 'Denied' }}</strong></div><div class="property"><span>Governed write path</span><strong [class]="statusClass(current.managementReady ? 'Ready' : 'Attention required')">{{ current.managementReady ? 'Ready' : 'Attention required' }}</strong></div><div class="property"><span>Current next action</span><strong>{{ nextAction(current) }}</strong></div><div class="property"><span>Evidence coverage</span><strong>{{ evidenceCoverage(current) }}</strong></div></section></div></div>
          </section>
        }

        @if (activeTab() === 'journey') {
          <section class="domain-workspace" role="tabpanel" aria-label="Change Journey">
            @if (current.changes[0]; as change) {
              <section class="journey-focus"><header><div><os-cicon [icon]="icons.commit" [size]="18" /><span><strong>{{ change.action }} · {{ change.target }}</strong><small><code>{{ change.request_id }}</code> · {{ formatDate(change.created_at) }}</small></span></div><strong [class]="statusClass(changeVerdict(change))">{{ changeVerdict(change) }}</strong></header><div class="journey-steps">@for (step of journeyFor(change); track step.key) { <article [class]="'journey-step ' + step.state"><os-cicon [icon]="step.state === 'done' ? icons.check : (step.state === 'failed' ? icons.warning : icons.pending)" [size]="15" /><span><strong>{{ step.label }}</strong><small>{{ step.evidence }}</small></span></article> }</div><footer><strong>다음 조치</strong><span>{{ changeNextAction(change) }}</span></footer></section>
              <section class="journey-evidence"><div><span>Repository</span><strong>{{ change.git_repo || current.supplyChain?.repository || '—' }}</strong></div><div><span>Signed merge</span><strong>{{ shortId(change.execution?.merge_revision || '') || 'evidence 없음' }}</strong></div><div><span>Approvals</span><strong>{{ change.approvals.length }}/{{ current.supplyChain?.requiredApprovals || 1 }}</strong></div><div><span>Outbox</span><strong>{{ change.outbox?.status || 'Not queued' }}</strong></div><div><span>Reconciler</span><strong>{{ change.execution?.reconciler_status || 'Awaiting consumer' }}</strong></div><div><span>Observed receipt</span><strong>{{ change.k8s_operation_id || '없음' }}</strong></div></section>
            } @else { <section class="journey-empty"><os-cicon [icon]="icons.pending" [size]="20" /><strong>아직 추적할 governed change가 없습니다.</strong><p>빈 상태는 검증 완료가 아닙니다. 첫 변경을 만들면 Supabase intent부터 Gitea 서명·승인, outbox와 Kubernetes receipt까지 여정이 생성됩니다.</p></section> }
          </section>
        }

        @if (activeTab() === 'repositories') {
          <section class="domain-workspace" role="tabpanel" aria-label="Repositories">
            <clr-datagrid><clr-dg-column>Repository</clr-dg-column><clr-dg-column>Visibility</clr-dg-column><clr-dg-column>Default branch</clr-dg-column><clr-dg-column>Size / updated</clr-dg-column>
              @for (repo of current.repositories; track repo.name) { <clr-dg-row><clr-dg-cell><strong>{{ repo.name }}</strong><small>{{ repo.archived ? 'archived' : (repo.empty ? 'empty' : 'active') }}</small></clr-dg-cell><clr-dg-cell><span class="label" [class.label-success]="repo.private" [class.label-warning]="!repo.private">{{ repo.private ? 'private' : 'public' }}</span></clr-dg-cell><clr-dg-cell><code>{{ repo.defaultBranch }}</code></clr-dg-cell><clr-dg-cell>{{ repo.sizeKiB }} KiB<small>{{ repo.updatedAt || '—' }}</small></clr-dg-cell></clr-dg-row> }<clr-dg-placeholder>Gitea repository inventory를 불러오는 중…</clr-dg-placeholder></clr-datagrid>
          </section>
        }

        @if (activeTab() === 'changes') {
          <section class="domain-workspace" role="tabpanel" aria-label="Changes">
            <section class="os-card"><div class="os-card-h">새 선언형 변경</div><p class="os-sub">의도는 Supabase에 먼저 기록된 다음 Gitea private branch와 PR로 전환됩니다. 원문에 password·token·credential·private key를 넣을 수 없습니다.</p>
              @if (requestedTemplate(); as template) { <div class="template-contract"><strong>고정 설치 계약</strong><span>{{ template.target }} · chart SHA-256 고정 · CRD → Operator/CSI → Runtime RBAC → Ready 검증</span></div> }
              <div class="form-grid"><label>Consumer<select [disabled]="!!requestedTemplate()" [value]="draft().consumerId" (change)="setDraft('consumerId', selectValue($event))">@for (contract of current.contracts; track contract.consumer_id) { <option [value]="contract.consumer_id">{{ contract.display_name || contract.consumer_id }}</option> }</select></label><label>Action<select [disabled]="!!requestedTemplate()" [value]="draft().action" (change)="setDraft('action', selectValue($event))"><option value="configure">configure</option><option value="apply">apply</option><option value="rollback">rollback</option></select></label><label class="wide">Target<input [readOnly]="!!requestedTemplate()" [value]="draft().target" (input)="setDraft('target', inputValue($event))" maxlength="300" /></label><label class="wide">Reason (8+ chars)<input [placeholder]="requestedTemplate()?.reasonPlaceholder || ''" [value]="draft().reason" (input)="setDraft('reason', inputValue($event))" maxlength="1000" /></label><label class="wide">Desired state (JSON)<textarea rows="8" [readOnly]="!!requestedTemplate()" [value]="draft().desiredState" (input)="setDraft('desiredState', inputValue($event))"></textarea></label></div>
              <button class="btn btn-primary" [disabled]="submitting() || !current.managementReady || draft().reason.trim().length < 8" (click)="submitChange()">{{ submitting() ? 'PR 생성 중…' : (requestedTemplate() ? '설치 PR 생성' : 'Gitea PR 생성') }}</button>
              @if (requestedTemplate(); as template) { <a class="btn btn-outline" [href]="template.returnTo">Ceph 준비 화면으로 돌아가기</a> }
            </section>
            <section class="os-card"><div class="os-card-h">최근 선언형 변경</div><clr-datagrid><clr-dg-column>Request</clr-dg-column><clr-dg-column>Action / target</clr-dg-column><clr-dg-column>Status</clr-dg-column><clr-dg-column>Gitea</clr-dg-column><clr-dg-column>Approval</clr-dg-column>
              @for (change of current.changes; track change.request_id) { <clr-dg-row><clr-dg-cell><code>{{ shortId(change.request_id) }}</code><small>{{ change.created_at }}</small></clr-dg-cell><clr-dg-cell><strong>{{ change.action }}</strong><small>{{ change.target }}</small></clr-dg-cell><clr-dg-cell><span class="label" [class.label-success]="change.status === 'applied'" [class.label-warning]="isPending(change.status)" [class.label-danger]="change.status === 'failed'">{{ change.status }}</span></clr-dg-cell><clr-dg-cell>@if (change.execution?.pull_url) { <a [href]="change.execution?.pull_url" target="_blank" rel="noopener">PR #{{ change.execution?.pull_number }}</a><small><code>{{ shortId(change.execution?.desired_revision || '') }}</code></small> } @else { <span class="muted">proposal 대기</span> }</clr-dg-cell><clr-dg-cell>{{ approvalLabel(change) }}<small>{{ change.approvals.length ? change.approvals[change.approvals.length - 1].completed_at || change.approvals[change.approvals.length - 1].created_at : '—' }}</small></clr-dg-cell></clr-dg-row> }<clr-dg-placeholder>기록된 선언형 변경이 없습니다.</clr-dg-placeholder></clr-datagrid></section>
          </section>
        }

        @if (activeTab() === 'approval') {
          <section class="domain-workspace" role="tabpanel" aria-label="Approval & Reconciliation">
            <section class="os-card"><div class="os-card-h">Second-operator approval</div><p class="os-sub">변경 생성자는 자신의 변경을 승인할 수 없습니다. 승인에는 MFA assurance (aal2)와 8자 이상의 사유가 필요합니다.</p><label class="approval-reason">Approval reason<input [value]="approvalReason()" (input)="approvalReason.set(inputValue($event))" maxlength="1000" /></label></section>
            <clr-datagrid><clr-dg-column>Request</clr-dg-column><clr-dg-column>PR / approval</clr-dg-column><clr-dg-column>Outbox</clr-dg-column><clr-dg-column>Reconciler</clr-dg-column><clr-dg-column>Action</clr-dg-column>
              @for (change of current.changes; track change.request_id) { <clr-dg-row><clr-dg-cell><code>{{ shortId(change.request_id) }}</code><small>{{ change.target }}</small></clr-dg-cell><clr-dg-cell>PR #{{ change.execution?.pull_number || '—' }}<small>{{ approvalLabel(change) }}</small></clr-dg-cell><clr-dg-cell>{{ change.outbox?.status || 'not queued' }}<small>attempts {{ change.outbox?.attempts || 0 }}</small></clr-dg-cell><clr-dg-cell>{{ change.execution?.reconciler || 'not assigned' }}<small>{{ change.execution?.reconciler_status || '—' }} · drift {{ change.execution?.drift_status || '—' }}</small></clr-dg-cell><clr-dg-cell>@if (change.status === 'authorized' && change.execution?.pull_number) { <button class="btn btn-sm btn-outline" [disabled]="approving() === change.request_id" (click)="approve(change)">{{ approving() === change.request_id ? '승인 중…' : '승인 및 merge' }}</button> } @else { <span class="muted">{{ change.k8s_operation_id || '대기' }}</span> }</clr-dg-cell></clr-dg-row> }<clr-dg-placeholder>reconcile 상관관계가 없습니다.</clr-dg-placeholder></clr-datagrid>
          </section>
        }

        @if (activeTab() === 'webhooks') {
          <section class="domain-workspace" role="tabpanel" aria-label="Webhooks">
            <p class="os-sub">Gitea HMAC signature를 검증한 receipt만 상태를 전진시킬 수 있습니다. payload 원문은 저장하지 않고 digest·delivery metadata만 보존합니다.</p><clr-datagrid><clr-dg-column>Delivery</clr-dg-column><clr-dg-column>Event</clr-dg-column><clr-dg-column>Signature</clr-dg-column><clr-dg-column>Disposition</clr-dg-column><clr-dg-column>Request / time</clr-dg-column>@for (receipt of current.receipts; track receipt.delivery_id) { <clr-dg-row><clr-dg-cell><code>{{ shortId(receipt.delivery_id) }}</code></clr-dg-cell><clr-dg-cell>{{ receipt.event_type }}<small>{{ receipt.repository || '—' }}</small></clr-dg-cell><clr-dg-cell><span class="label" [class.label-success]="receipt.signature_valid" [class.label-danger]="!receipt.signature_valid">{{ receipt.signature_valid ? 'valid' : 'rejected' }}</span></clr-dg-cell><clr-dg-cell>{{ receipt.disposition }}<small>{{ receipt.error_code || '—' }}</small></clr-dg-cell><clr-dg-cell><code>{{ shortId(receipt.request_id || '') }}</code><small>{{ receipt.received_at }}</small></clr-dg-cell></clr-dg-row>}<clr-dg-placeholder>webhook receipt가 없습니다.</clr-dg-placeholder></clr-datagrid>
          </section>
        }

        @if (activeTab() === 'supply-chain') {
          <section class="domain-workspace" role="tabpanel" aria-label="Supply Chain">
            @if (current.supplyChain; as policy) { <section class="os-card"><div class="os-card-h">{{ policy.repository }} · {{ policy.defaultBranch }}</div><div class="policy-grid"><div><span>Branch protected</span><strong [class.ok]="policy.protected">{{ policy.protected ? 'Enforced' : 'Missing' }}</strong></div><div><span>Direct push</span><strong [class.ok]="!policy.directPushEnabled">{{ policy.directPushEnabled ? 'Allowed' : 'Denied' }}</strong></div><div><span>Required approvals</span><strong [class.ok]="policy.requiredApprovals >= 1">{{ policy.requiredApprovals }}</strong></div><div><span>Signed commits</span><strong [class.ok]="policy.signedCommitsRequired">{{ policy.signedCommitsRequired ? 'Required' : 'Not enforced' }}</strong></div><div><span>Rejected review blocks merge</span><strong [class.ok]="policy.blockRejectedReviews">{{ policy.blockRejectedReviews ? 'Enforced' : 'Not enforced' }}</strong></div></div><p class="os-sub">Gitea server의 SSH signing key는 server-only Secret과 in-memory volume에서만 사용됩니다. Console API가 만드는 선언 커밋과 승인된 merge commit은 해당 키로 서명됩니다.</p></section> } @else { <p class="os-sub">Gitea branch policy를 읽을 수 없습니다.</p> }
          </section>
        }

        @if (activeTab() === 'dr-contracts') {
          <section class="domain-workspace" role="tabpanel" aria-label="DR & Contracts">
            @if (current.recovery?.available && current.recovery?.gitea; as recovery) { <section class="os-card recovery-detail"><div class="os-card-h"><span>Gitea recovery evidence</span><strong [class]="statusClass(recoveryVerdict(recovery))">{{ recoveryVerdict(recovery) }}</strong></div><p class="os-sub">{{ formatDate(recovery.verifiedAt) }} · 선언 상태 {{ recovery.declaredState || recovery.state }}</p>@if (recovery.checks?.length) { <div class="check-table"><div class="check-head"><span>Assertion</span><span>Expected</span><span>Observed</span><span>Verdict</span></div>@for (check of recovery.checks || []; track check.assertion) { <div><strong>{{ check.assertion }}</strong><span>{{ check.expected }}</span><span>{{ check.observed }}</span><span [class]="statusClass(check.verdict)">{{ check.verdict === 'Verified' ? 'Verified' : 'Insufficient evidence' }}</span></div> }</div> } @else { <ul>@for (assertion of recovery.assertions || []; track assertion) { <li class="os-mono">{{ assertion }}</li> }</ul> }</section> } @else { <p class="os-sub">{{ current.recovery?.reason || 'Recovery evidence unavailable' }}</p> }
            <clr-datagrid><clr-dg-column>Consumer contract</clr-dg-column><clr-dg-column>Supabase scope</clr-dg-column><clr-dg-column>Gitea path / reconciler</clr-dg-column><clr-dg-column>Observed state</clr-dg-column>@for (contract of current.contracts; track contract.consumer_id) { <clr-dg-row><clr-dg-cell><strong>{{ contract.display_name }}</strong><small>{{ contract.consumer_id }} · {{ contract.status }}</small></clr-dg-cell><clr-dg-cell>{{ join(contract.supabase_schemas) || '—' }}<small>{{ join(contract.storage_buckets) || 'Storage 미사용' }}</small></clr-dg-cell><clr-dg-cell><code>{{ contract.gitea_path }}</code><small>{{ contract.reconciler }}</small></clr-dg-cell><clr-dg-cell>{{ contract.observability?.phase || 'NotConfigured' }}<small>{{ contract.observability?.binding_name || 'HIS Binding 없음' }}</small></clr-dg-cell></clr-dg-row>}<clr-dg-placeholder>consumer contract가 없습니다.</clr-dg-placeholder></clr-datagrid><p class="os-sub">HIS Binding이 없으면 Console은 Prometheus/HIS를 생성하지 않고 NotConfigured으로 표시합니다. Binding이 제공한 telemetry freshness만 관측 화면에서 사용합니다.</p>
          </section>
        }
      }
    </div>
  `,
  styles: [`
    .overview-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.journey-focus{margin:.85rem 0;border:1px solid var(--os-hairline);background:var(--os-canvas)}.journey-focus>header{display:flex;align-items:center;justify-content:space-between;gap:.75rem;padding:.65rem .75rem;border-bottom:1px solid var(--os-hairline)}.journey-focus>header>div{display:flex;align-items:center;gap:.45rem}.journey-focus>header span{display:grid;gap:.08rem}.journey-focus>header strong{font-size:.72rem}.journey-focus>header small{color:var(--os-ink-muted);font-size:.56rem}.journey-steps{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:.4rem;padding:.75rem}.journey-step{display:flex;align-items:flex-start;gap:.35rem;min-width:0;padding:.5rem;border:1px solid var(--os-hairline);color:var(--os-ink-muted)}.journey-step.done{color:var(--os-success)}.journey-step.waiting{border-color:var(--os-accent);color:var(--os-accent)}.journey-step.failed{border-color:var(--os-danger);color:var(--os-danger)}.journey-step span{display:grid;min-width:0}.journey-step strong{overflow:hidden;color:var(--os-ink);font-size:.57rem;text-overflow:ellipsis;white-space:nowrap}.journey-step small{overflow:hidden;font-size:.5rem;text-overflow:ellipsis;white-space:nowrap}.journey-focus>footer{display:flex;gap:.5rem;padding:.55rem .75rem;border-top:1px solid var(--os-hairline);font-size:.62rem}.journey-focus>footer span{color:var(--os-ink-muted)}.journey-evidence{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));margin:.75rem 0;border:1px solid var(--os-hairline);background:var(--os-canvas)}.journey-evidence div{display:grid;gap:.15rem;padding:.65rem;border-right:1px solid var(--os-hairline);border-bottom:1px solid var(--os-hairline)}.journey-evidence div:nth-child(3n){border-right:0}.journey-evidence span{color:var(--os-ink-muted);font-size:.57rem}.journey-evidence strong{font-size:.65rem;overflow-wrap:anywhere}.journey-empty{display:grid;justify-items:start;gap:.35rem;margin:.85rem 0;padding:1rem;border:1px solid var(--os-hairline);background:var(--os-canvas);color:var(--os-ink-muted)}.journey-empty strong{color:var(--os-ink);font-size:.72rem}.journey-empty p{max-width:48rem;margin:0;font-size:.64rem;line-height:1.5}.recovery-detail .os-card-h{display:flex;justify-content:space-between;gap:.75rem}.check-table{display:grid;font-size:.64rem}.check-table>div{display:grid;grid-template-columns:minmax(12rem,1.4fr) .65fr .65fr 1fr;gap:.5rem;padding:.42rem 0;border-bottom:1px solid var(--os-hairline)}.check-table>div:last-child{border-bottom:0}.check-table .check-head{color:var(--os-ink-muted);font-size:.57rem}.status-label{display:inline-flex;align-items:center;gap:.25rem}.ok{color:var(--os-success)!important}.warn{color:#a15c00!important}.danger{color:var(--os-danger)!important}.waiting{color:var(--os-accent)!important}.neutral{color:var(--os-ink-muted)!important}
    .os-sub{color:var(--os-ink-muted);font-size:.72rem;margin:.3rem 0 .8rem}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem;margin:.85rem 0}.summary-grid section{display:grid;gap:.25rem;padding:1rem;border:1px solid var(--os-hairline);background:var(--os-canvas)}.summary-grid span,.summary-grid small,small,.muted{color:var(--os-ink-muted);font-size:.64rem}.summary-grid strong{color:var(--os-accent);font-size:1.1rem;overflow-wrap:anywhere}.os-card{margin:0;padding:.8rem 1rem;border:1px solid var(--os-hairline);background:var(--os-canvas)}.os-card-h{margin:-.8rem -1rem .7rem;padding:.55rem .8rem;border-bottom:1px solid var(--os-hairline);background:var(--os-surface-1);font-weight:600;font-size:.8rem}.chain{padding:.4rem 0;display:flex;gap:.45rem;flex-wrap:wrap;align-items:center}.chain span{background:#e8f0ff;color:#164a9b;padding:.25rem .45rem;font-size:.7rem;font-weight:600}.chain b{color:var(--os-ink-muted)}.property{display:grid;grid-template-columns:11rem minmax(0,1fr);gap:.5rem;font-size:.75rem;margin:.5rem 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin:.7rem 0}.form-grid label,.approval-reason{display:grid;gap:.25rem;font-size:.7rem;color:var(--os-ink-muted)}.form-grid .wide{grid-column:1/-1}.form-grid input,.form-grid textarea,.form-grid select,.approval-reason input{width:100%;font:inherit;padding:.4rem;border:1px solid var(--os-hairline);background:var(--os-canvas);color:inherit}.approval-reason{max-width:44rem}.policy-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.65rem}.policy-grid div{display:grid;gap:.2rem;border:1px solid var(--os-hairline);padding:.65rem}.policy-grid span{color:var(--os-ink-muted);font-size:.65rem}.policy-grid strong{color:var(--os-danger)}.policy-grid strong.ok{color:var(--os-success, #147a3d)}clr-dg-cell{display:grid;gap:.18rem}ul{margin:.4rem 0;padding-left:1.2rem}li{margin:.25rem 0}.os-mono{font-family:monospace;font-size:.64rem}@media (max-width: 64rem){.summary-grid{grid-template-columns:repeat(2, minmax(0, 1fr))}.policy-grid{grid-template-columns:repeat(2, minmax(0, 1fr))}}@media (max-width: 48rem){.summary-grid,.form-grid,.policy-grid{grid-template-columns:1fr}.property{grid-template-columns:1fr}}
    .template-contract{display:grid;gap:.2rem;padding:.7rem;border-left:.2rem solid var(--os-accent);background:var(--os-surface-1);font-size:.68rem}.template-contract span{color:var(--os-ink-muted)}.form-grid input[readonly],.form-grid textarea[readonly],.form-grid select:disabled{background:var(--os-surface-1);color:var(--os-ink-muted)}
    @media (max-width:64rem){.journey-steps{grid-template-columns:repeat(4,minmax(0,1fr))}}@media (max-width:48rem){.overview-columns,.journey-evidence{grid-template-columns:1fr}.journey-evidence div{border-right:0;border-bottom:1px solid var(--os-hairline)}.journey-steps{grid-template-columns:1fr}.check-table>div{grid-template-columns:1fr 1fr}.check-table .check-head{display:none}}
  `],
})
export class AdminChangeControl implements OnInit, OnDestroy {
  readonly icons = { arrow: ArrowRight16, check: CheckmarkFilled16, warning: WarningAltFilled16, pending: Pending16, commit: Commit16, renew: Renew16 };
  readonly activeTab = signal<'overview' | 'journey' | 'repositories' | 'changes' | 'approval' | 'webhooks' | 'supply-chain' | 'dr-contracts'>('overview');
  readonly state = signal<ChangeControlState | null>(null); readonly down = signal(''); readonly busy = signal(false); readonly submitting = signal(false); readonly approving = signal(''); readonly approvalReason = signal(''); readonly message = signal<{ type: 'danger' | 'success' | 'warning' | 'info'; text: string } | null>(null);
  readonly requestedTemplate = signal<ChangeTemplate | null>(null);
  readonly draft = signal({ consumerId: 'extensions', action: 'configure', target: 'extensions', reason: '', desiredState: '{\n  "enabled": true\n}' }); readonly managementReady = computed(() => this.state()?.managementReady ?? false);
  private readonly http = inject(HttpService); private readonly route = inject(ActivatedRoute); private timer: ReturnType<typeof setInterval> | null = null;
  async ngOnInit(): Promise<void> { await this.loadRequestedTemplate(); await this.refresh(); this.timer = setInterval(() => void this.refresh(true), 20_000); }
  ngOnDestroy(): void { if (this.timer) clearInterval(this.timer); }
  shortId(value: string | null | undefined): string { return String(value || '').slice(0, 12); } join(value: string[] | null | undefined): string { return (value || []).join(', '); } isPending(status: string): boolean { return ['intent', 'authorized', 'committed'].includes(status); } inFlight(value: ChangeControlState): number { return (value.byStatus['intent'] || 0) + (value.byStatus['authorized'] || 0) + (value.byStatus['committed'] || 0); } inputValue(event: Event): string { return (event.target as HTMLInputElement | HTMLTextAreaElement).value; } selectValue(event: Event): string { return (event.target as HTMLSelectElement).value; }
  formatDate(value: string | null | undefined): string { if (!value) return '기록 없음'; const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(date) + ' KST'; }
  statusClass(value: string | null | undefined): string { const normalized = String(value || '').toLowerCase(); if (/failed|unavailable|missing|allowed/.test(normalized)) return 'status-label danger'; if (/attention|insufficient|incomplete/.test(normalized)) return 'status-label warn'; if (/awaiting|pending|authorized|committed/.test(normalized)) return 'status-label waiting'; if (/notconfigured|not configured|unknown|not queued/.test(normalized)) return 'status-label neutral'; return 'status-label ok'; }
  approvedCount(value: ChangeControlState): number { return value.changes.reduce((total, change) => total + change.approvals.filter((approval) => approval.status === 'approved').length, 0); }
  boundContractCount(value: ChangeControlState): number { return value.contracts.filter((contract) => contract.observability?.phase === 'Bound').length; }
  evidenceCoverage(value: ChangeControlState): string { const policy = value.supplyChain; const policyChecks = policy ? [policy.protected, !policy.directPushEnabled, policy.signedCommitsRequired, policy.requiredApprovals >= 1, policy.blockRejectedReviews].filter(Boolean).length : 0; return `${policyChecks}/5 policy gates · ${value.receipts.length} receipts`; }
  nextAction(value: ChangeControlState): string { if (!value.ready) return 'Gitea 연결 복구'; if (!value.managementReady) return 'service token / webhook secret 확인'; if (!value.changes.length) return '첫 governed change 생성'; const latest = value.changes[0]; return this.changeNextAction(latest); }
  changeVerdict(change: ChangeRequest): string { if (change.status === 'failed' || change.execution?.last_error || change.outbox?.last_error) return 'Failed'; if (change.status === 'applied' && change.k8s_operation_id) return 'Observed'; if (['committed', 'authorized'].includes(change.status) || /await|pending|queued/i.test(change.execution?.reconciler_status || change.outbox?.status || '')) return 'Awaiting consumer'; return change.status === 'intent' ? 'Attention required' : 'Awaiting consumer'; }
  changeNextAction(change: ChangeRequest): string { const verdict = this.changeVerdict(change); if (verdict === 'Failed') return '실패한 outbox 또는 reconcile 단계 수정'; if (verdict === 'Observed') return 'observed state와 drift 증거 검토'; if (!change.execution?.pull_number) return 'Gitea PR 생성 상태 확인'; if (!change.approvals.some((item) => item.status === 'approved')) return '두 번째 운영자 승인'; if (!change.execution?.merge_revision) return '보호 브랜치 merge 확인'; return 'consumer reconciler 등록 또는 receipt 확인'; }
  journeyFor(change: ChangeRequest): JourneyItem[] { const approved = change.approvals.some((item) => item.status === 'approved'); const merged = Boolean(change.execution?.merge_revision || change.git_commit_sha); const outboxDone = /sent|delivered|completed/i.test(change.outbox?.status || ''); const failed = this.changeVerdict(change) === 'Failed'; return [
    { key: 'intent', label: 'Supabase intent', evidence: this.shortId(change.request_id), state: 'done' },
    { key: 'audit', label: 'Audit correlation', evidence: 'request recorded', state: 'done' },
    { key: 'pr', label: 'Signed PR', evidence: change.execution?.pull_number ? `#${change.execution.pull_number}` : 'not created', state: change.execution?.pull_number ? 'done' : 'waiting' },
    { key: 'approval', label: 'Second approval', evidence: `${change.approvals.length}/1`, state: approved ? 'done' : (failed ? 'failed' : 'waiting') },
    { key: 'merge', label: 'Protected merge', evidence: this.shortId(change.execution?.merge_revision || '') || 'not merged', state: merged ? 'done' : 'waiting' },
    { key: 'outbox', label: 'Webhook / outbox', evidence: change.outbox?.status || 'not queued', state: failed ? 'failed' : (outboxDone ? 'done' : 'waiting') },
    { key: 'observed', label: 'Runtime observed', evidence: change.k8s_operation_id || 'receipt 없음', state: failed ? 'failed' : (change.status === 'applied' && change.k8s_operation_id ? 'done' : 'waiting') },
  ]; }
  recoveryVerdict(unit: RecoveryUnit): string { if (/attention|insufficient|failed|unknown/i.test(unit.state)) return 'Attention required'; if (unit.checks?.some((check) => check.verdict !== 'Verified')) return 'Attention required'; if (unit.assertions.some((assertion) => /^(users|repositories)=0$/i.test(assertion.trim()))) return 'Attention required'; return unit.state === 'Verified' ? 'Verified' : unit.state; }
  setDraft(key: 'consumerId' | 'action' | 'target' | 'reason' | 'desiredState', value: string): void { this.draft.update((draft) => ({ ...draft, [key]: value, ...(key === 'consumerId' && draft.target === 'extensions' ? { target: value } : {}) })); }
  approvalLabel(change: ChangeRequest): string { const latest = change.approvals[change.approvals.length - 1]; return latest ? latest.status : 'awaiting second operator'; }
  async loadRequestedTemplate(): Promise<void> { const templateId = this.route.snapshot.queryParamMap.get('template'); if (!templateId) return; this.busy.set(true); try { const response = await this.http.request(`/api/platform/change-templates/${encodeURIComponent(templateId)}`, { cache: 'no-store' }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(String(result.error || `HTTP ${response.status}`)); const template = result as ChangeTemplate; this.requestedTemplate.set(template); this.draft.set({ consumerId: template.consumerId, action: template.action, target: template.target, reason: '', desiredState: JSON.stringify(template.desiredState, null, 2) }); this.activeTab.set('changes'); } catch (error) { this.message.set({ type: 'danger', text: `설치 요청서 로드 실패: ${String(error)}` }); } finally { this.busy.set(false); } }
  async submitChange(): Promise<void> { const draft = this.draft(); let desiredState: object; try { desiredState = JSON.parse(draft.desiredState) as object; } catch { this.message.set({ type: 'danger', text: 'Desired state는 유효한 JSON object여야 합니다.' }); return; } if (!desiredState || Array.isArray(desiredState)) { this.message.set({ type: 'danger', text: 'Desired state는 JSON object여야 합니다.' }); return; } this.submitting.set(true); try { const response = await this.http.request('/api/platform/changes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...draft, desiredState, ...(this.requestedTemplate() ? { templateId: this.requestedTemplate()!.id } : {}) }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(String(result.error || `HTTP ${response.status}`)); this.message.set({ type: 'success', text: result.duplicate ? `기존 요청 ${result.requestId}을 사용합니다.` : `Gitea PR #${result.pullRequest?.number || '—'}을 생성했습니다. 두 번째 운영자 승인 후 설치와 Ready 검증이 자동 실행됩니다.` }); this.activeTab.set('approval'); await this.refresh(true); } catch (error) { this.message.set({ type: 'danger', text: `변경 생성 실패: ${String(error)}` }); } finally { this.submitting.set(false); } }
  async approve(change: ChangeRequest): Promise<void> { const reason = this.approvalReason().trim(); if (reason.length < 8) { this.message.set({ type: 'warning', text: '승인 사유를 8자 이상 입력하세요.' }); return; } this.approving.set(change.request_id); try { const response = await this.http.request(`/api/platform/changes/${encodeURIComponent(change.request_id)}/approve`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ reason }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(String(result.error || `HTTP ${response.status}`)); this.message.set({ type: 'success', text: result.merged ? '승인과 Gitea merge가 완료되었습니다. webhook/reconciler receipt를 대기합니다.' : '승인은 기록됐고 merge 결과를 확인 중입니다.' }); this.approvalReason.set(''); await this.refresh(true); } catch (error) { this.message.set({ type: 'danger', text: `승인 또는 merge 실패: ${String(error)}` }); } finally { this.approving.set(''); } }
  async refresh(silent = false): Promise<void> { if (!silent) this.busy.set(true); try { const response = await this.http.request('/api/platform/gitea/status', { cache: 'no-store' }); if (!response.ok) { this.down.set(`Gitea 상태 HTTP ${response.status}`); return; } const next = await response.json() as ChangeControlState; this.state.set(next); if (!this.requestedTemplate() && next.contracts.length && !next.contracts.some((contract) => contract.consumer_id === this.draft().consumerId)) { const first = next.contracts[0]; this.draft.update((draft) => ({ ...draft, consumerId: first.consumer_id, target: first.consumer_id })); } this.down.set(''); } catch (error) { this.down.set(`Gitea 상태 조회 실패: ${String(error)}`); } finally { if (!silent) this.busy.set(false); } }
}
