-- 0032 — 원장 무결성: TRUNCATE 차단과 해시 사슬 실체화
--
-- arch-002 레드팀 감사 L2-7 시정.
--
-- 결함 1. append-only 트리거가 `BEFORE UPDATE OR DELETE ... FOR EACH ROW` 뿐이었다.
--   PostgreSQL 에서 TRUNCATE 는 **statement-level** 트리거로만 잡힌다. 따라서 UPDATE/DELETE 는
--   막히지만 `TRUNCATE audit.event` 한 줄로 원장 전체를 비울 수 있었고 트리거는 발동조차 하지 않았다.
--   이 저장소에 이미 올바른 패턴이 하나 있다(0024 `model_registry_approval_audit_no_truncate`).
--   나머지 10개 append-only 테이블에 같은 보호를 붙인다.
--
-- 결함 2. `audit.event.prev_hash` 컬럼이 선언만 되고 채우는 writer 가 없었다.
--   해시 사슬이 장식이었고, 행이 지워지거나 순서가 바뀌어도 탐지할 근거가 없었다.
--   서버가 삽입 시점에 직접 채운다 — 클라이언트가 보낸 값은 신뢰하지 않고 덮어쓴다.
--
-- ⚠ `event_hash` 는 건드리지 않는다. 기존 writer 들이 `ON CONFLICT (request_id, phase, event_hash)`
--   로 멱등성을 얻고 있어(0003·0007·0009·0010), 서버가 다시 계산하면 재시도가 중복 삽입이 된다.
--   `event_hash` = 내용 요약(멱등 키), `prev_hash` = 사슬 링크. 역할을 분리해 둔다.

BEGIN;

-- ── 1. 삽입 순서를 확정하는 단조 시퀀스 ───────────────────────────────────────
-- `occurred_at` 은 clock_timestamp() 라 동시 삽입에서 동률이 날 수 있어 사슬 순서로 쓸 수 없다.
ALTER TABLE audit.event
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS audit_event_seq_idx ON audit.event (seq);

-- ── 1b. 기존 행의 사슬을 소급해 세운다 ───────────────────────────────────────
--
-- ⚠ 정직하게 적어 둔다. 이 백필은 **이 마이그레이션 이전의 무결성을 증명하지 않는다.**
--   0032 이전에 행이 지워졌다면 그 사실은 이미 복구 불가능하고, 백필은 남아 있는 행들로
--   일관된 사슬을 새로 만들 뿐이다. 사슬이 증거가 되는 구간은 **0032 적용 시점 이후**다.
--   백필을 하지 않으면 `verify_event_chain()` 이 기존 행 전부를 파손으로 보고해
--   진짜 파손을 가려 버리므로(경보 피로), 시작점을 정리하는 것이다.
--
-- append-only 트리거를 잠시 내린다. 스키마 진화를 위한 일회성 조치이며 같은 트랜잭션 안에서
-- 되올린다. event 내용과 event_hash 는 건드리지 않는다 — 비어 있던 prev_hash 만 채운다.
ALTER TABLE audit.event DISABLE TRIGGER audit_event_append_only;

WITH ordered AS (
  SELECT e.id, LAG(e.event_hash) OVER (ORDER BY e.seq) AS expected_prev
  FROM audit.event e
)
UPDATE audit.event t
   SET prev_hash = o.expected_prev
  FROM ordered o
 WHERE t.id = o.id
   AND t.prev_hash IS DISTINCT FROM o.expected_prev;

ALTER TABLE audit.event ENABLE ALWAYS TRIGGER audit_event_append_only;

-- ── 2. prev_hash 를 서버가 채운다 ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION audit.link_event_chain()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, audit
AS $$
DECLARE
  last_hash text;
BEGIN
  -- 사슬은 직렬화되어야 의미가 있다. 두 삽입이 같은 선행 행을 읽으면 분기가 생긴다.
  -- 감사 삽입량은 낮으므로 처리량보다 정합성을 택한다.
  PERFORM pg_advisory_xact_lock(hashtext('audit.event.chain'));

  SELECT e.event_hash INTO last_hash
  FROM audit.event e
  ORDER BY e.seq DESC
  LIMIT 1;

  -- 클라이언트가 무엇을 보냈든 서버 값으로 덮는다. 위조된 링크를 받지 않는다.
  NEW.prev_hash := last_hash;   -- 최초 행은 NULL(사슬의 뿌리)
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_event_chain_link ON audit.event;
CREATE TRIGGER audit_event_chain_link
  BEFORE INSERT ON audit.event
  FOR EACH ROW EXECUTE FUNCTION audit.link_event_chain();
ALTER TABLE audit.event ENABLE ALWAYS TRIGGER audit_event_chain_link;

-- ── 3. 사슬을 실제로 검증할 수 있게 한다 ──────────────────────────────────────
-- "해시 사슬이 있다" 는 주장은 검증 함수가 있어야 확인 가능한 주장이 된다.
-- 끊어진 첫 지점을 돌려준다. 정상이면 0행.
CREATE OR REPLACE FUNCTION audit.verify_event_chain()
RETURNS TABLE (seq bigint, id uuid, occurred_at timestamptz, expected_prev text, actual_prev text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, audit
AS $$
  WITH chained AS (
    SELECT e.seq, e.id, e.occurred_at, e.prev_hash,
           LAG(e.event_hash) OVER (ORDER BY e.seq) AS expected_prev
    FROM audit.event e
  )
  SELECT c.seq, c.id, c.occurred_at, c.expected_prev, c.prev_hash
  FROM chained c
  WHERE c.expected_prev IS DISTINCT FROM c.prev_hash
  ORDER BY c.seq;
$$;

REVOKE ALL ON FUNCTION audit.verify_event_chain() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION audit.verify_event_chain() TO opensphere_console_backend, service_role;

-- ── 4. TRUNCATE 차단 — append-only 테이블 전수 ────────────────────────────────
-- 각 테이블은 이미 자기 거부 함수를 갖고 있다. statement-level 트리거만 없었다.
DROP TRIGGER IF EXISTS audit_event_no_truncate ON audit.event;
CREATE TRIGGER audit_event_no_truncate
  BEFORE TRUNCATE ON audit.event
  FOR EACH STATEMENT EXECUTE FUNCTION audit.reject_mutation();
ALTER TABLE audit.event ENABLE ALWAYS TRIGGER audit_event_no_truncate;

DROP TRIGGER IF EXISTS image_revocation_no_truncate ON console.image_revocation;
CREATE TRIGGER image_revocation_no_truncate
  BEFORE TRUNCATE ON console.image_revocation
  FOR EACH STATEMENT EXECUTE FUNCTION console.reject_image_revocation_mutation();
ALTER TABLE console.image_revocation ENABLE ALWAYS TRIGGER image_revocation_no_truncate;

DROP TRIGGER IF EXISTS schema_migration_no_truncate ON console.schema_migration;
CREATE TRIGGER schema_migration_no_truncate
  BEFORE TRUNCATE ON console.schema_migration
  FOR EACH STATEMENT EXECUTE FUNCTION console.reject_schema_migration_mutation();
ALTER TABLE console.schema_migration ENABLE ALWAYS TRIGGER schema_migration_no_truncate;

DROP TRIGGER IF EXISTS llm_usage_event_no_truncate ON oaa.llm_usage_event;
CREATE TRIGGER llm_usage_event_no_truncate
  BEFORE TRUNCATE ON oaa.llm_usage_event
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_llm_usage_mutation();
ALTER TABLE oaa.llm_usage_event ENABLE ALWAYS TRIGGER llm_usage_event_no_truncate;

DROP TRIGGER IF EXISTS retrieval_trace_no_truncate ON oaa.retrieval_trace;
CREATE TRIGGER retrieval_trace_no_truncate
  BEFORE TRUNCATE ON oaa.retrieval_trace
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.retrieval_trace ENABLE ALWAYS TRIGGER retrieval_trace_no_truncate;

DROP TRIGGER IF EXISTS tool_run_no_truncate ON oaa.tool_run;
CREATE TRIGGER tool_run_no_truncate
  BEFORE TRUNCATE ON oaa.tool_run
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.tool_run ENABLE ALWAYS TRIGGER tool_run_no_truncate;

DROP TRIGGER IF EXISTS agent_step_no_truncate ON oaa.agent_step;
CREATE TRIGGER agent_step_no_truncate
  BEFORE TRUNCATE ON oaa.agent_step
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.agent_step ENABLE ALWAYS TRIGGER agent_step_no_truncate;

DROP TRIGGER IF EXISTS runtime_event_no_truncate ON oaa.runtime_event;
CREATE TRIGGER runtime_event_no_truncate
  BEFORE TRUNCATE ON oaa.runtime_event
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.runtime_event ENABLE ALWAYS TRIGGER runtime_event_no_truncate;

DROP TRIGGER IF EXISTS evidence_policy_event_no_truncate ON oaa.evidence_policy_event;
CREATE TRIGGER evidence_policy_event_no_truncate
  BEFORE TRUNCATE ON oaa.evidence_policy_event
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.evidence_policy_event ENABLE ALWAYS TRIGGER evidence_policy_event_no_truncate;

DROP TRIGGER IF EXISTS evidence_export_receipt_no_truncate ON oaa.evidence_export_receipt;
CREATE TRIGGER evidence_export_receipt_no_truncate
  BEFORE TRUNCATE ON oaa.evidence_export_receipt
  FOR EACH STATEMENT EXECUTE FUNCTION oaa.reject_evidence_mutation();
ALTER TABLE oaa.evidence_export_receipt ENABLE ALWAYS TRIGGER evidence_export_receipt_no_truncate;

-- ── 5. 권한에서도 TRUNCATE 를 뺀다 ────────────────────────────────────────────
-- 트리거는 최후 방어선이다. 권한 자체를 주지 않는 것이 먼저다.
REVOKE TRUNCATE ON audit.event, console.image_revocation, console.schema_migration
  FROM anon, authenticated, service_role;
REVOKE TRUNCATE ON oaa.llm_usage_event, oaa.retrieval_trace, oaa.tool_run,
  oaa.agent_step, oaa.runtime_event, oaa.evidence_policy_event, oaa.evidence_export_receipt
  FROM anon, authenticated, service_role;

COMMIT;
