import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const source = fs.readFileSync(path.join(root, 'Publish-LocalEdgeBackendComponent.ps1'), 'utf8');
const deployer = fs.readFileSync(path.join(root, 'Invoke-LocalEdgePlatformRelease.ps1'), 'utf8');

test('Backend publisher is a dedicated single-image, dual-source, signed component authority', () => {
  assert.match(source, /docker buildx build --platform linux\/amd64 --push/);
  assert.match(source, /opensphere-console-backend/);
  assert.match(source, /--build-context "setup-cli=\$detachedSetup"/);
  assert.match(source, /New-DetachedTree \$console\.Path \$console\.Revision/);
  assert.match(source, /New-DetachedTree \$setup\.Path \$setup\.Revision/);
  assert.match(source, /Join-Path \$detachedConsole 'scripts\\Invoke-LocalEdgePlatformRelease\.ps1'/);
  assert.match(source, /Detached deployer differs from the signed committed tooling evidence/);
  assert.doesNotMatch(source, /Join-Path \$PSScriptRoot 'Invoke-LocalEdgePlatformRelease\.ps1'\s*\r?\n\$apply/);
  assert.match(source, /git -C \$resolved status --porcelain=v1 --untracked-files=all/);
  assert.match(source, /SETUP_SOURCE_REVISION=\$\(\$setup\.Revision\)/);
  assert.match(source, /status --porcelain=v1 --untracked-files=all/);
  assert.match(source, /branch -cne 'main'/);
  assert.match(source, /upstream -cne 'origin\/main'/);
  assert.match(source, /fetch --quiet origin main/);
  assert.match(source, /repository-inventory\.json/);
  assert.match(source, /https:\/\/github\.com\/opensphere-platform\/OpenSphere-Platform-V2\.git/);
  assert.match(source, /platformAuthority=/);
  assert.match(source, /inventory=\$inventoryEvidence/);
  assert.match(source, /changedPaths=@\(\$changedPaths\)/);
  assert.match(source, /affectedImages=@\('backend'\)/);
  assert.match(source, /New-OsShellEdgeSignedDocument/);
  assert.match(source, /Invoke-LocalEdgePlatformRelease\.ps1/);
  assert.doesNotMatch(source, /-Operation converge|convergeComponentRelease/);
  assert.match(source, /setup-source\.lock/);
  assert.match(source, /lockSha256=\$setupLockSha256/);
  assert.match(source, /manifestProjectionTool=\$setupProjectionTool/);
  assert.match(source, /Invoke-BootstrapManifestProjection/);
  assert.match(source, /platform-release-bootstrap-manifest\.mjs/);
  assert.match(source, /-BootstrapFrom \$bootstrapFrom/);
  assert.match(source, /Signed Backend B publication requires canonical migration 0063/);
  assert.match(source, /initializer=Get-CommittedTool/);
  assert.match(source, /fresh-ledger-verifier/);
  assert.match(source, /rendered-manifest-server-dry-run/);
  assert.match(source, /verificationSetDigest/);
  assert.match(source, /ParameterSetName = 'SignedB'\)\]\[string\]\$BootstrapFromEvidence/);
  assert.match(source, /ParameterSetName = 'BootstrapA'\)\]\[switch\]\$BootstrapA/);
  assert.match(source, /opensphere-backend-component-bootstrap-a-publication\/v1/);
  assert.match(source, /Assert-BootstrapAPathClosure/);
  assert.match(source, /function Assert-BootstrapAManifestSource/);
  assert.match(source, /function Assert-BootstrapADockerfileSource/);
  assert.match(source, /src\/platform-release-bootstrap-cleanup\.mjs/);
  assert.doesNotMatch(source, /if \(-not \$BootstrapA\)[\s\S]{0,240}src\/platform-release-bootstrap-cleanup\.mjs/);
  assert.match(source, /opensphere-bootstrap-a-initializer-cleanup-journal-custody/);
  assert.match(source, /bootstrap-a-invoke-fixture/);
  assert.match(source, /-PlatformAuthorityPath \$workspaceRoot -SetupAuthorityPath \$setup\.Path/);
  assert.match(source, /Backend Bootstrap A manifest contains a final-convergence dependency/);
  assert.match(source, /Backend Bootstrap A must retain the installed migration set exactly/);
  assert.match(source, /& \$deployer -BootstrapA -PublicationEvidence/);
  assert.match(source, /-TrustedPublicKeySpkiBase64 \$signed\.PublicKeySpkiBase64 -ExpectedKeyId \$SigningKeyId/);
  assert.match(source, /convergenceState=if \(\$BootstrapA\) \{ 'PendingConvergence' \}/);
  assert.match(source, /foundationFeatureGate=if \(\$BootstrapA\) \{ 'Closed' \}/);
  assert.match(source, /latestMigrationId=\[string\]\$migration\.latestMigrationId/);
  assert.match(source, /function Get-ValidatedBootstrapFrom/);
  assert.match(source, /opensphere-backend-component-bootstrap\/v1/);
  assert.match(source, /bootstrapFrom=if \(\$BootstrapA\) \{ \$null \} else \{ \$bootstrapFrom \}/);
  assert.match(source, /value\.image -cne \$ExpectedImage/);
  assert.match(source, /value\.sourceRevision -cne \$ExpectedSourceRevision/);
  assert.doesNotMatch(source, /Publish-LocalEdge\.ps1/);
  assert.doesNotMatch(source, /Publish-LocalEdgeComponent\.ps1/);
});

test('governed deployer uses in-memory TLS request without insecure curl', () => {
  assert.match(deployer, /#requires -Version 7\.2/);
  assert.match(deployer, /Invoke-RestMethod -Method Post/);
  assert.match(deployer, /Invoke-RestMethod -Method Get/);
  assert.match(deployer, /create token opensphere-local-edge-release/);
  assert.match(deployer, /publicationDocumentBase64/);
  assert.match(deployer, /publicationSignature/);
  assert.match(deployer, /expectedTerminalPhase = if \(\$mode -eq 'BootstrapA'\) \{ 'BootstrapApplied' \} else \{ 'Completed' \}/);
  assert.match(deployer, /\[ValidateRange\(3100, 7200\)\]\[int\]\$TimeoutSeconds = 3600/);
  assert.match(deployer, /DefaultParameterSetName = 'Submit'/);
  assert.match(deployer, /ParameterSetName = 'Resume'/);
  assert.match(deployer, /\[switch\]\$Resume/);
  assert.match(deployer, /function Assert-BootstrapASourceEvidence/);
  assert.match(deployer, /function Assert-BootstrapARequestPendingProof/);
  assert.match(deployer, /opensphere-backend-bootstrap-a-resume-proof\/v1/);
  assert.match(deployer, /Bootstrap A signed changedPaths differ from the exact previous-to-target Console diff/);
  assert.match(deployer, /Bootstrap A verification artifact is missing or changed/);
  assert.match(deployer, /opensphere-local-edge-platform-release-resume\/v1/);
  assert.match(deployer, /if \(\$PSCmdlet\.ParameterSetName -ne 'Resume'\)/);
  assert.match(deployer, /Save-ResumeState \$resumePath \$requestId \$targetReleaseDigest 'Applying'/);
  assert.match(deployer, /Save-ResumeState \$resumePath \$requestId \$targetReleaseDigest 'NeedsAttention'/);
  assert.match(deployer, /Resume only this exact durable operation/);
  assert.match(deployer, /Resume state already exists; resume it instead of submitting another mutation/);
  assert.match(deployer, /-TimeoutSec 120/);
  assert.doesNotMatch(deployer, /-TimeoutSec \(\$TimeoutSeconds \+ 30\)/);
  assert.doesNotMatch(deployer, /--insecure|curl\.exe/);
});

test('Platform response-loss retry compares one normalized exact Job before accepting 409', () => {
  const reconciler = fs.readFileSync(path.join(root, '..', 'backend',
    'opensphere-console-backend', 'platform-release-reconciler.js'), 'utf8');
  assert.match(reconciler, /if \(error\.status !== 409\) throw error/);
  assert.match(reconciler, /kubernetesRequest\(\s*'GET'/);
  assert.match(reconciler, /if \(!sameExecutorJob\(existing, job\)\)/);
  assert.match(reconciler, /normalizedExecutorJob\(actual, true\)/);
  assert.match(reconciler, /podReplacementPolicy !== 'TerminatingOrFailed'/);
  assert.match(reconciler, /terminationMessagePath !== '\/dev\/termination-log'/);
});
