import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const read = (...parts) => fs.readFileSync(path.join(here, ...parts), 'utf8');
const manifest = read('bootstrap', 'supabase.yaml');
const schema = read('migrations', '0001_console_backbone.sql');
const boundary = read('migrations', '0002_backend_boundary.sql');
const correlation = read('migrations', '0003_change_correlation.sql');
const oaa = read('migrations', '0005_oaa_governed_agent.sql');
const cliIdentity = read('migrations', '0006_cli_identity.sql');
const extensionRevocation = read('migrations', '0007_extension_revocation.sql');
const backendServiceRole = read('migrations', '0008_backend_service_role.sql');
const governance = read('migrations', '0009_platform_control_governance.sql');
const approval = read('migrations', '0010_change_approval.sql');
const notification = read('migrations', '0011_notification_delivery.sql');
const llmUsage = read('migrations', '0012_oaa_llm_usage_ledger.sql');
const agentControlPlane = read('migrations', '0013_oaa_agent_control_plane.sql');
const cliTokenScope = read('migrations', '0014_cli_token_scope.sql');
const knowledgeRevisions = read('migrations', '0015_oaa_knowledge_revisions.sql');
const runtimeWatch = read('migrations', '0016_oaa_runtime_watch.sql');
const watchObserver = read('migrations', '0017_oaa_watch_observer.sql');
const ownerApiProjection = read('migrations', '0018_oaa_owner_api_projection.sql');
const evidenceCorrelation = read('migrations', '0019_oaa_evidence_correlation_retention.sql');
const ownerControlPermissions = read('migrations', '0020_oaa_owner_control_permissions.sql');
const infrastructureOwnerPermissions = read('migrations', '0021_oaa_infrastructure_owner_permissions.sql');
const recoveryOwnerPermissions = read('migrations', '0022_oaa_recovery_owner_permissions.sql');
const cephPrerequisiteConsumer = read('migrations', '0023_ceph_prerequisite_consumer.sql');
const aiConsumerContract = read('migrations', '0024_ai_consumer_contract.sql');
const externalChannelsBackup = read('migrations', '0025_external_channels_backup.sql');
const migrationLedger = read('migrations', '0026_schema_migration_ledger.sql');
const externalChannelReasonPolicy = read('migrations', '0027_external_channel_reason_policy.sql');
const browserSessionAndMonitoring = read('migrations', '0029_browser_session_and_baseline_monitoring.sql');
const moduleOperationLedger = read('migrations', '0035_module_operation_ledger.sql');
const browserSessionExpiryEvidence = read('migrations', '0037_browser_session_expiry_evidence.sql');
const watchCursorStatusVocabulary = read('migrations', '0038_oaa_watch_cursor_status_vocabulary.sql');
const externalBackupS3CompatibleProfiles = read('migrations', '0043_external_backup_s3_compatible_profiles.sql');
const externalBackupTlsTrust = read('migrations', '0044_external_backup_target_tls_trust.sql');
const storageEntrypoint = read('images', 'storage', 'opensphere-storage-entrypoint.sh');
const storageDockerfile = read('images', 'storage', 'Dockerfile');
const installer = read('install.ps1');
const nginx = fs.readFileSync(path.join(here, '..', '..', 'nginx', 'default.conf.template'), 'utf8');

assert.match(installer, /\[string\]\$Namespace = "opensphere-console-data"/);
assert.match(installer, /\.Replace\("__OPENSPHERE_SUPABASE_NAMESPACE__", \$Namespace\)/);
assert.match(installer, /Get-ChildItem[\s\S]+-Filter '\*\.sql'[\s\S]+Sort-Object Name/);
assert.match(installer, /function Invoke-SupabaseMigrationPsql/);
assert.match(installer, /supabase_admin -d postgres -v ON_ERROR_STOP=1/);
assert.match(installer, /function Get-SupabaseMigrationChecksums/);
assert.match(installer, /Canonical = Get-TextSha256 \$lf/);
assert.match(installer, /recordedChecksum -notin @\(\$checksums\.Canonical, \$checksums\.Crlf, \$checksums\.Raw\)/);
assert.match(installer, /if \(-not \$ExistingInstallation\) \{[\s\S]+opensphere-supabase-auth[\s\S]+opensphere-supabase-storage/);
assert.match(installer, /elseif \(\$appliedMigrationCount -gt 0\)[\s\S]+NOTIFY pgrst, 'reload schema'/);
assert.match(installer, /\[string\]\$SourceRevision/);
assert.match(installer, /SourceRevision must be the immutable 40-character release commit SHA/);
assert.match(installer, /function Get-SupabaseMigrationChecksum/);
assert.match(installer, /Migration checksum drift/);
assert.match(installer, /Supabase migration \$migrationId already attested/);
assert.match(installer, /foreach \(\$migration in \$migrations\)/);
assert.match(installer, /Invoke-SupabaseMigrationPsql \(Get-Content -Raw -LiteralPath \$migration\.FullName\)/);
assert.match(installer, /foreach \(\$workload in @\('opensphere-supabase-auth', 'opensphere-supabase-storage'\)\)[\s\S]+foreach \(\$migration in \$migrations\)/);
assert.match(installer, /foreach \(\$migration in \$migrations\)[\s\S]+foreach \(\$workload in @\('opensphere-supabase-rest', 'opensphere-supabase-storage'\)\)/);
assert.doesNotMatch(installer, /--from-literal/);
assert.match(manifest, /supabase\/postgres:17\.6\.1\.136/);
assert.match(manifest, /supabase\/gotrue:v2\.189\.0/);
assert.match(manifest, /supabase\/storage-api:v1\.60\.4/);
assert.match(manifest, /OPENSPHERE_STORAGE_DATABASE_HOST/);
assert.match(manifest, /OPENSPHERE_STORAGE_REST_HOST/);
assert.match(manifest, /startupProbe:\s*\n\s+exec: \{ command: \["\/bin\/sh", "-c", "pg_isready -U postgres -d postgres"\] \}\s*\n\s+failureThreshold: 60\s*\n\s+periodSeconds: 5/);
assert.match(manifest, /startupProbe: \{ httpGet: \{ path: \/health, port: http \}, failureThreshold: 60, periodSeconds: 5 \}/);
assert.match(manifest, /startupProbe: \{ httpGet: \{ path: \/live, port: admin \}, failureThreshold: 60, periodSeconds: 5 \}/);
assert.match(manifest, /startupProbe:[\s\S]+failureThreshold: 180/);
assert.equal([...manifest.matchAll(/startupProbe:/g)].length, 4);
assert.equal([...manifest.matchAll(/name: wait-for-postgres/g)].length, 2);
assert.equal([...manifest.matchAll(/image: docker\.io\/supabase\/postgres:17\.6\.1\.136/g)].length, 3);
assert.match(manifest, /psql -h opensphere-supabase-postgres\.__OPENSPHERE_SUPABASE_NAMESPACE__\.svc\.cluster\.local -U supabase_auth_admin -d postgres/);
assert.match(manifest, /psql -h opensphere-supabase-postgres\.__OPENSPHERE_SUPABASE_NAMESPACE__\.svc\.cluster\.local -U authenticator -d postgres/);
assert.match(storageDockerfile, /ENTRYPOINT \["\/usr\/local\/bin\/opensphere-storage-entrypoint\.sh"\]/);
assert.match(storageEntrypoint, /getent hosts "\$service_host"/);
assert.match(storageEntrypoint, /nc -z -w 2 "\$service_host" "\$service_port"/);
assert.match(storageEntrypoint, /exec \/usr\/local\/bin\/docker-entrypoint\.sh "\$@"/);
assert.match(manifest, /postgrest\/postgrest:v14\.12/);
assert.doesNotMatch(manifest, /image:\s+[^\n]+:latest\b/);
assert.doesNotMatch(manifest, /service-role-key[^\n]*value:/);
assert.doesNotMatch(manifest, /postgres-password[^\n]*value:/);
assert.match(manifest, /opensphere-supabase-default-deny/);

assert.match(schema, /user_id uuid PRIMARY KEY REFERENCES auth\.users\(id\)/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS console\.change_request/);
assert.match(schema, /git_commit_sha text CHECK/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS audit\.event/);
assert.match(schema, /CREATE TRIGGER audit_event_append_only/);
assert.match(schema, /ALTER TABLE audit\.event ENABLE ROW LEVEL SECURITY/);
assert.match(schema, /REVOKE INSERT, UPDATE, DELETE[\s\S]+audit\.event FROM anon, authenticated/);
assert.match(schema, /owner_id = auth\.uid\(\)/);
assert.match(boundary, /NOBYPASSRLS|NO-BYPASSRLS/);
assert.match(boundary, /REVOKE UPDATE, DELETE, TRUNCATE ON audit\.event/);
assert.match(correlation, /FUNCTION console\.begin_change/);
assert.match(correlation, /FUNCTION console\.record_change_commit/);
assert.match(correlation, /FUNCTION console\.record_reconcile_result/);
assert.match(correlation, /ON CONFLICT \(idempotency_key\)/);
assert.match(correlation, /GRANT EXECUTE[\s\S]+opensphere_console_backend/);
assert.match(oaa, /CREATE SCHEMA IF NOT EXISTS oaa/);
assert.match(oaa, /CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions/);
assert.match(oaa, /CREATE TABLE IF NOT EXISTS oaa\.document_version/);
assert.match(oaa, /CREATE TABLE IF NOT EXISTS oaa\.embedding/);
assert.match(oaa, /search_vector tsvector GENERATED ALWAYS/);
assert.match(oaa, /oaa\.knowledge\.read/);
assert.match(oaa, /ALTER TABLE oaa\.oaa_knowledge_documents ENABLE ROW LEVEL SECURITY/);
assert.match(oaa, /opensphere_oaa_gateway/);
assert.match(cliIdentity, /CREATE TABLE IF NOT EXISTS console\.cli_device/);
assert.match(cliIdentity, /CREATE TABLE IF NOT EXISTS console\.api_token/);
assert.match(cliIdentity, /FUNCTION console\.approve_cli_enrollment/);
assert.match(cliIdentity, /poll_token_hash text NOT NULL/);
assert.match(cliIdentity, /opensphere_console_backend/);
assert.match(cliIdentity, /DROP POLICY IF EXISTS console_backend_cli_device/);
assert.match(extensionRevocation, /CREATE TABLE IF NOT EXISTS console\.image_revocation/);
assert.match(extensionRevocation, /CREATE TRIGGER image_revocation_append_only/);
assert.match(extensionRevocation, /REVOKE INSERT, UPDATE, DELETE, TRUNCATE[\s\S]+anon, authenticated/);
assert.match(extensionRevocation, /FUNCTION console\.revoke_image/);
assert.match(extensionRevocation, /INSERT INTO audit\.event/);
assert.match(extensionRevocation, /GRANT USAGE ON SCHEMA console, audit TO service_role/);
assert.match(extensionRevocation, /GRANT SELECT, INSERT ON audit\.event TO service_role/);
assert.match(backendServiceRole, /GRANT opensphere_console_backend TO authenticator/);
assert.match(backendServiceRole, /REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA console FROM service_role/);
assert.match(backendServiceRole, /GRANT SELECT ON console\.image_revocation TO service_role/);
assert.match(backendServiceRole, /GRANT SELECT, INSERT ON audit\.event TO service_role/);
assert.match(backendServiceRole, /GRANT EXECUTE ON FUNCTION console\.revoke_image/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.consumer_contract/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.gitea_webhook_receipt/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.change_outbox/);
assert.match(governance, /FUNCTION console\.record_change_proposal/);
assert.match(governance, /FUNCTION console\.queue_change_reconcile/);
assert.match(governance, /REVOKE ALL ON FUNCTION console\.record_change_proposal[\s\S]+anon, authenticated/);
assert.match(approval, /CREATE TABLE IF NOT EXISTS console\.change_approval/);
assert.match(approval, /FUNCTION console\.begin_change_approval/);
assert.match(approval, /change creator cannot approve their own request/);
assert.match(notification, /CREATE TABLE IF NOT EXISTS console\.notification_channel/);
assert.match(notification, /CREATE TABLE IF NOT EXISTS console\.notification_delivery/);
assert.match(notification, /opensphere_notification_dispatcher/);
assert.match(notification, /ENABLE ROW LEVEL SECURITY/);
assert.match(notification, /DROP POLICY IF EXISTS console_backend_notification_channel/);
assert.match(notification, /DROP POLICY IF EXISTS dispatcher_notification_control/);
assert.match(externalChannelReasonPolicy, /DROP CONSTRAINT IF EXISTS configuration_restore_reason_check/);
assert.doesNotMatch(externalChannelReasonPolicy, /length\s*\(\s*btrim\s*\(\s*reason\s*\)\s*\)\s*>=\s*8/i);
assert.match(browserSessionAndMonitoring, /CREATE TABLE IF NOT EXISTS console\.browser_session/);
assert.match(browserSessionAndMonitoring, /access_token_ciphertext text NOT NULL/);
assert.match(browserSessionAndMonitoring, /refresh_token_ciphertext text NOT NULL/);
assert.match(browserSessionAndMonitoring, /persistence IN \('browser', '8h', '24h', '7d'\)/);
assert.match(browserSessionAndMonitoring, /ALTER TABLE console\.browser_session FORCE ROW LEVEL SECURITY/);
assert.match(browserSessionAndMonitoring, /REVOKE ALL ON TABLE console\.browser_session FROM PUBLIC, anon, authenticated, service_role/);
assert.match(browserSessionAndMonitoring, /CREATE TABLE IF NOT EXISTS console\.session_event/);
assert.match(browserSessionAndMonitoring, /CREATE TABLE IF NOT EXISTS console\.infrastructure_node_binding/);
assert.match(browserSessionAndMonitoring, /beszel_machine_fingerprint text NOT NULL/);
assert.match(browserSessionAndMonitoring, /console\.infrastructure\.read/);
assert.match(browserSessionAndMonitoring, /console\.infrastructure\.manage/);
assert.match(browserSessionExpiryEvidence, /DROP CONSTRAINT IF EXISTS session_event_event_check/);
assert.match(browserSessionExpiryEvidence, /'refresh_rejected'/);
assert.match(browserSessionExpiryEvidence, /'expired_idle'/);
assert.match(browserSessionExpiryEvidence, /'expired_absolute'/);
assert.match(browserSessionExpiryEvidence, /'authority_unavailable'/);
assert.match(watchCursorStatusVocabulary, /DROP CONSTRAINT IF EXISTS watch_cursor_status_check/);
for (const state of ['starting', 'discovery', 'discovery-error', 'watching', 'reconnecting', 'stopped', 'error', 'unsupported']) {
  assert.match(watchCursorStatusVocabulary, new RegExp(`'${state}'`));
}
assert.match(installer, /browser-session-key/);
assert.match(installer, /New-RandomBase64 32/);
assert.match(installer, /\[switch\]\$ExistingInstallation/);
assert.match(installer, /function Set-WorkloadStartupProbe/);
assert.match(installer, /Set-WorkloadStartupProbe 'statefulset\/opensphere-supabase-postgres' 'postgres'/);
assert.match(installer, /function Set-DatabaseDependentStartupContract/);
assert.match(installer, /Set-DatabaseDependentStartupContract 'deployment\/opensphere-supabase-auth' 'auth'/);
assert.match(installer, /Set-DatabaseDependentStartupContract 'deployment\/opensphere-supabase-rest' 'rest'/);
assert.match(installer, /Existing PostgreSQL image is not an exact governed digest/);
assert.match(installer, /release-pinned images preserved and startup safety reconciled/);
assert.match(installer, /if \(-not \$ExistingInstallation\)[\s\S]+Invoke-Kubectl @\("apply", "-f", "-"\) \$renderedManifest/);
assert.match(llmUsage, /CREATE TABLE IF NOT EXISTS oaa\.llm_usage_event/);
assert.match(llmUsage, /request_id uuid NOT NULL UNIQUE/);
assert.match(llmUsage, /input_tokens bigint NOT NULL DEFAULT 0/);
assert.match(llmUsage, /output_tokens bigint NOT NULL DEFAULT 0/);
assert.match(llmUsage, /cached_input_tokens bigint NOT NULL DEFAULT 0/);
assert.match(llmUsage, /reasoning_tokens bigint NOT NULL DEFAULT 0/);
assert.match(llmUsage, /CREATE TRIGGER llm_usage_event_append_only/);
assert.match(llmUsage, /ENABLE ALWAYS TRIGGER llm_usage_event_append_only/);
assert.match(llmUsage, /REVOKE ALL ON oaa\.llm_usage_event FROM PUBLIC, anon, authenticated/);
assert.match(llmUsage, /GRANT SELECT, INSERT ON oaa\.llm_usage_event TO opensphere_oaa_gateway/);
assert.match(llmUsage, /oaa\.usage\.read/);
assert.match(llmUsage, /never stores API keys, prompts, responses, or bearer tokens/i);
assert.match(agentControlPlane, /CREATE TABLE IF NOT EXISTS oaa\.runtime_resource/);
assert.match(agentControlPlane, /CREATE TABLE IF NOT EXISTS oaa\.agent_run/);
assert.match(agentControlPlane, /CREATE TABLE IF NOT EXISTS oaa\.agent_step/);
assert.match(agentControlPlane, /FUNCTION console\.claim_change_reconcile/);
assert.match(agentControlPlane, /FOR UPDATE OF o SKIP LOCKED/);
assert.match(agentControlPlane, /retrieval_trace_append_only/);
assert.match(agentControlPlane, /tool_run_append_only/);
assert.match(agentControlPlane, /REVOKE UPDATE, DELETE, TRUNCATE ON oaa\.retrieval_trace, oaa\.tool_run, oaa\.agent_step/);
assert.match(cliTokenScope, /scope IN \('console-read', 'console-change', 'console-admin'\)/);
assert.match(knowledgeRevisions, /ADD COLUMN IF NOT EXISTS document_revision/);
assert.match(knowledgeRevisions, /UNIQUE \(document_id, document_revision, chunk_index\)/);
assert.match(knowledgeRevisions, /ON DELETE RESTRICT/);
assert.match(runtimeWatch, /CREATE TABLE IF NOT EXISTS oaa\.runtime_event/);
assert.match(runtimeWatch, /CREATE TABLE IF NOT EXISTS oaa\.watch_cursor/);
assert.match(runtimeWatch, /CREATE TRIGGER runtime_event_append_only/);
assert.match(runtimeWatch, /payload_digest text NOT NULL/);
assert.match(runtimeWatch, /REVOKE UPDATE, DELETE, TRUNCATE ON oaa\.runtime_event/);
assert.match(watchObserver, /ADD COLUMN IF NOT EXISTS observer_id/);
assert.match(watchObserver, /PRIMARY KEY \(source, observer_id, kind, namespace\)/);
assert.match(ownerApiProjection, /runtime_resource_source_freshness_idx/);
assert.match(ownerApiProjection, /runtime_event_source_observed_idx/);
assert.match(ownerApiProjection, /owner-API state changes/);
assert.match(evidenceCorrelation, /ADD COLUMN IF NOT EXISTS agent_run_id/);
assert.match(evidenceCorrelation, /CREATE TABLE IF NOT EXISTS oaa\.evidence_retention_policy/);
assert.match(evidenceCorrelation, /CREATE TABLE IF NOT EXISTS oaa\.evidence_export_receipt/);
assert.match(evidenceCorrelation, /FUNCTION oaa\.set_evidence_retention_policy/);
assert.match(evidenceCorrelation, /No purge API is exposed/);
assert.match(ownerControlPermissions, /console\.extension\.security\.read/);
assert.match(ownerControlPermissions, /console\.extension\.security\.manage/);
assert.match(ownerControlPermissions, /console\.notification\.read/);
assert.match(ownerControlPermissions, /console\.notification\.manage/);
assert.match(ownerControlPermissions, /role\.code = 'console-operators'/);
assert.match(infrastructureOwnerPermissions, /console\.his\.read/);
assert.match(infrastructureOwnerPermissions, /console\.his\.manage/);
assert.match(infrastructureOwnerPermissions, /console\.ceph\.read/);
assert.match(infrastructureOwnerPermissions, /console\.ceph\.manage/);
assert.match(infrastructureOwnerPermissions, /role\.code = 'console-operators'/);
assert.match(recoveryOwnerPermissions, /console\.recovery\.read/);
assert.match(recoveryOwnerPermissions, /role\.code IN \('console-admins', 'console-operators'\)/);
assert.match(cephPrerequisiteConsumer, /'ceph-prerequisites'/);
assert.match(cephPrerequisiteConsumer, /opensphere\.ceph\.rook-prerequisite\/v1/);
assert.match(aiConsumerContract, /opensphere_ai_runtime/);
assert.match(aiConsumerContract, /ai-artifacts/);
assert.match(externalChannelsBackup, /opensphere_external_channel_executor/);
assert.match(externalChannelsBackup, /external_backup_secret/);
assert.match(externalChannelsBackup, /restore_configuration_snapshot/);
assert.match(externalChannelsBackup, /configuration-backup\.opensphere\.io\/v1/);
assert.match(externalBackupS3CompatibleProfiles, /ALTER COLUMN vendor SET DEFAULT 's3-compatible'/);
assert.match(externalBackupS3CompatibleProfiles, /external_backup_target_endpoint_check/);
assert.match(externalBackupS3CompatibleProfiles, /AWS Signature Version 4 compatible S3 API/);
assert.doesNotMatch(externalBackupS3CompatibleProfiles, /vendor\s*=\s*'backblaze-b2'/);
assert.match(externalBackupTlsTrust, /tls_trust_mode IN \('system', 'custom-ca'\)/);
assert.match(externalBackupTlsTrust, /custom_ca_fingerprint/);
assert.doesNotMatch(externalBackupTlsTrust, /NODE_TLS_REJECT_UNAUTHORIZED|rejectUnauthorized\s*=\s*false/);
assert.match(migrationLedger, /CREATE TABLE IF NOT EXISTS console\.schema_migration/);
assert.match(migrationLedger, /sha256 text NOT NULL/);
assert.match(migrationLedger, /source_revision text NOT NULL/);
assert.match(migrationLedger, /schema_migration_append_only/);
assert.match(migrationLedger, /REVOKE ALL ON TABLE console\.schema_migration FROM PUBLIC/);
assert.match(moduleOperationLedger, /CREATE TABLE IF NOT EXISTS console\.module_operation/);
assert.match(moduleOperationLedger, /idempotency_key text NOT NULL UNIQUE/);
assert.match(moduleOperationLedger, /target_fingerprint text NOT NULL/);
assert.match(moduleOperationLedger, /'Queued', 'AwaitingApproval', 'Running', 'Verifying'/);
assert.match(moduleOperationLedger, /FORCE ROW LEVEL SECURITY/);
assert.match(moduleOperationLedger, /GRANT SELECT, INSERT, UPDATE ON TABLE console\.module_operation TO opensphere_console_backend/);
assert.match(nginx, /location \^~ \/auth\/v1\//);
assert.match(nginx, /opensphere-supabase-auth\.opensphere-console-data\.svc\.cluster\.local/);
assert.match(nginx, /location \^~ \/storage\/v1\//);
assert.match(nginx, /rewrite \^\/storage\/v1\/\(\.\*\)\$ \/\$1 break/);
assert.match(nginx, /proxy_request_buffering off/);

console.log('Supabase backbone static contract: PASS');
