import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const read = (...parts) => fs.readFileSync(path.join(here, ...parts), 'utf8');
const manifest = read('bootstrap', 'supabase.yaml');
const schema = read('migrations', '0001_console_backbone.sql');
const boundary = read('migrations', '0002_backend_boundary.sql');
const correlation = read('migrations', '0003_change_correlation.sql');
const oaa = read('migrations', '0005_oaa_governed_agent.sql');
const cliIdentity = read('migrations', '0006_cli_identity.sql');
const extensionRevocation = read('migrations', '0007_extension_revocation.sql');
const backendServiceRole = read('migrations', '0008_backend_service_role.sql');
const governance = read('migrations', '0009_platform_control_governance.sql');
const approval = read('migrations', '0010_change_approval.sql');
const installer = read('install.ps1');
const nginx = fs.readFileSync(path.join(here, '..', '..', 'nginx', 'default.conf.template'), 'utf8');

assert.match(installer, /\[string\]\$Namespace = "opensphere-console-data"/);
assert.match(installer, /\.Replace\("__OPENSPHERE_SUPABASE_NAMESPACE__", \$Namespace\)/);
assert.match(manifest, /supabase\/postgres:17\.6\.1\.136/);
assert.match(manifest, /supabase\/gotrue:v2\.189\.0/);
assert.match(manifest, /supabase\/storage-api:v1\.60\.4/);
assert.match(manifest, /postgrest\/postgrest:v14\.12/);
assert.doesNotMatch(manifest, /image:\s+[^\n]+:latest\b/);
assert.doesNotMatch(manifest, /service-role-key[^\n]*value:/);
assert.doesNotMatch(manifest, /postgres-password[^\n]*value:/);
assert.match(manifest, /opensphere-supabase-default-deny/);

assert.match(schema, /user_id uuid PRIMARY KEY REFERENCES auth\.users\(id\)/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS console\.change_request/);
assert.match(schema, /git_commit_sha text CHECK/);
assert.match(schema, /CREATE TABLE IF NOT EXISTS audit\.event/);
assert.match(schema, /CREATE TRIGGER audit_event_append_only/);
assert.match(schema, /ALTER TABLE audit\.event ENABLE ROW LEVEL SECURITY/);
assert.match(schema, /REVOKE INSERT, UPDATE, DELETE[\s\S]+audit\.event FROM anon, authenticated/);
assert.match(schema, /owner_id = auth\.uid\(\)/);
assert.match(boundary, /NOBYPASSRLS|NO-BYPASSRLS/);
assert.match(boundary, /REVOKE UPDATE, DELETE, TRUNCATE ON audit\.event/);
assert.match(correlation, /FUNCTION console\.begin_change/);
assert.match(correlation, /FUNCTION console\.record_change_commit/);
assert.match(correlation, /FUNCTION console\.record_reconcile_result/);
assert.match(correlation, /ON CONFLICT \(idempotency_key\)/);
assert.match(correlation, /GRANT EXECUTE[\s\S]+opensphere_console_backend/);
assert.match(oaa, /CREATE SCHEMA IF NOT EXISTS oaa/);
assert.match(oaa, /CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions/);
assert.match(oaa, /CREATE TABLE IF NOT EXISTS oaa\.document_version/);
assert.match(oaa, /CREATE TABLE IF NOT EXISTS oaa\.embedding/);
assert.match(oaa, /search_vector tsvector GENERATED ALWAYS/);
assert.match(oaa, /oaa\.knowledge\.read/);
assert.match(oaa, /ALTER TABLE oaa\.oaa_knowledge_documents ENABLE ROW LEVEL SECURITY/);
assert.match(oaa, /opensphere_oaa_gateway/);
assert.match(cliIdentity, /CREATE TABLE IF NOT EXISTS console\.cli_device/);
assert.match(cliIdentity, /CREATE TABLE IF NOT EXISTS console\.api_token/);
assert.match(cliIdentity, /FUNCTION console\.approve_cli_enrollment/);
assert.match(cliIdentity, /poll_token_hash text NOT NULL/);
assert.match(cliIdentity, /opensphere_console_backend/);
assert.match(extensionRevocation, /CREATE TABLE IF NOT EXISTS console\.image_revocation/);
assert.match(extensionRevocation, /CREATE TRIGGER image_revocation_append_only/);
assert.match(extensionRevocation, /REVOKE INSERT, UPDATE, DELETE, TRUNCATE[\s\S]+anon, authenticated/);
assert.match(extensionRevocation, /FUNCTION console\.revoke_image/);
assert.match(extensionRevocation, /INSERT INTO audit\.event/);
assert.match(extensionRevocation, /GRANT USAGE ON SCHEMA console, audit TO service_role/);
assert.match(extensionRevocation, /GRANT SELECT, INSERT ON audit\.event TO service_role/);
assert.match(backendServiceRole, /GRANT opensphere_console_backend TO authenticator/);
assert.match(backendServiceRole, /REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA console FROM service_role/);
assert.match(backendServiceRole, /GRANT SELECT ON console\.image_revocation TO service_role/);
assert.match(backendServiceRole, /GRANT SELECT, INSERT ON audit\.event TO service_role/);
assert.match(backendServiceRole, /GRANT EXECUTE ON FUNCTION console\.revoke_image/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.consumer_contract/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.gitea_webhook_receipt/);
assert.match(governance, /CREATE TABLE IF NOT EXISTS console\.change_outbox/);
assert.match(governance, /FUNCTION console\.record_change_proposal/);
assert.match(governance, /FUNCTION console\.queue_change_reconcile/);
assert.match(governance, /REVOKE ALL ON FUNCTION console\.record_change_proposal[\s\S]+anon, authenticated/);
assert.match(approval, /CREATE TABLE IF NOT EXISTS console\.change_approval/);
assert.match(approval, /FUNCTION console\.begin_change_approval/);
assert.match(approval, /change creator cannot approve their own request/);
assert.match(nginx, /location \^~ \/auth\/v1\//);
assert.match(nginx, /opensphere-supabase-auth\.opensphere-console-data\.svc\.cluster\.local/);
assert.match(nginx, /location \^~ \/storage\/v1\//);
assert.match(nginx, /rewrite \^\/storage\/v1\/\(\.\*\)\$ \/\$1 break/);
assert.match(nginx, /proxy_request_buffering off/);

console.log('Supabase backbone static contract: PASS');
